version: '3.7'

volumes:
  orderer.drx.network:
  peer0.clinicians.xmed.ai:
  peer0.scientists.xnome.net:

networks:
  vitaledge_net:
    name: vitaledge_net

services:

  orderer.drx.network:
    container_name: orderer.drx.network
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.drx.network:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/drx.network/orderers/orderer.drx.network/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/drx.network/orderers/orderer.drx.network/tls:/var/hyperledger/orderer/tls
      - orderer.drx.network:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - vitaledge_net

  peer0.clinicians.xmed.ai:
    container_name: peer0.clinicians.xmed.ai
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.clinicians.xmed.ai
      - CORE_PEER_ADDRESS=peer0.clinicians.xmed.ai:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.clinicians.xmed.ai:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.clinicians.xmed.ai:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.clinicians.xmed.ai:7051
      - CORE_PEER_LOCALMSPID=CliniciansMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.clinicians.xmed.ai:9444
      - CORE_METRICS_PROVIDER=prometheus
    volumes:
      - ../organizations/peerOrganizations/clinicians.xmed.ai/peers/peer0.clinicians.xmed.ai:/etc/hyperledger/fabric
      - peer0.clinicians.xmed.ai:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - vitaledge_net

  peer0.scientists.xnome.net:
    container_name: peer0.scientists.xnome.net
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.scientists.xnome.net
      - CORE_PEER_ADDRESS=peer0.scientists.xnome.net:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.scientists.xnome.net:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.scientists.xnome.net:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.scientists.xnome.net:9051
      - CORE_PEER_LOCALMSPID=ScientistsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.scientists.xnome.net:9445
      - CORE_METRICS_PROVIDER=prometheus
    volumes:
      - ../organizations/peerOrganizations/scientists.xnome.net/peers/peer0.scientists.xnome.net:/etc/hyperledger/fabric
      - peer0.scientists.xnome.net:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9445:9445
    networks:
      - vitaledge_net

  # vitaledge-rest-api:
  #   container_name: vitaledge-rest-api
  #   image: vitaledge/rest-api:latest # Custom-built API image
  #   build:
  #     context: ../rest-api # Adjust this path to your actual REST API code location
  #     dockerfile: Dockerfile  # Adjust if your Dockerfile has a different name
  #   environment:
  #     - FABRIC_CFG_PATH=/etc/hyperledger/fabric
  #     - ORDERER_CA=/etc/hyperledger/fabric/orderer/tls/ca.crt
  #     - ORDERER_ADDRESS=orderer.drx.network:7050
  #     - CHANNEL_NAME=vitaledgechannel
  #     - CHAINCODE_NAME=vitaledgechaincode
  #   ports:
  #     - 8080:8080               # REST API listens on port 8080
  #   volumes:
  #     - ../rest-api:/usr/src/app # Mount REST API code for development
  #   networks:
  #     - vitaledge_net
